---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: get existing wallet password
  command: "cat {{ e2dc_install_path }}//data/prysm/validator/passwords/wallet-password"
  register: existing_password
  become: yes
  become_user: "{{ stereum_user }}"

- name: Generate wallet password
  shell: uuidgen
  register: wallet_password_gen 
  when: existing_password.sdtout == ""

- name: Set wallet password
  copy:
    content: "{{ wallet_password_gen.stdout }}"
    dest: "{{ e2dc_install_path }}//data/prysm/validator/passwords/wallet-password"
  become: yes
  become_user: "{{ stereum_user }}"
  when: existing_password.sdtout == ""

- name: Run import
  ansible.builtin.expect:  
    command: "docker-compose -f create-account.yaml run validator-import-launchpad"
    timeout: 10
    responses:
       'to accept this terms': "accept"
       'the password for your imported accounts': "{{ validator_password }}"
       'Password incorrect for key': "\x03"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
  when: setups[setup].create_account is defined

# EOF
