---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: get existing wallet password
  command: "cat {{ e2dc_install_path }}//data/prysm/validator/passwords/wallet-password"
  register: existing_password
  become: yes
  become_user: "{{ stereum_user }}"

- name: Generate wallet password
  shell: uuidgen
  register: wallet_password_gen 
  when: existing_password.stdout == ""

- name: Set wallet password
  copy:
    content: "{{ wallet_password_gen.stdout }}"
    dest: "{{ e2dc_install_path }}//data/prysm/validator/passwords/wallet-password"
  become: yes
  become_user: "{{ stereum_user }}"
  when: existing_password.stdout == ""

- name: Run import  
  command: "./prysm_validator_import.sh \"{{ validator_password }}\""
  args:
    chdir: "{{ e2dc_install_path }}"
  register: import_output  
  become: yes
  become_user: "{{ stereum_user }}"
  when: setups[setup].create_account is defined

- name: error incorrect password
  fail:
    msg: "Incorrect Password!!! Please check your validator password and try it again."
  become: yes
  when: "'Password incorrect for key' in import_output.stdout"

# EOF
