---
- hosts: localhost
  connection: local
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    - name: call stop-services role
      include_role:
        name: stop-services
      when: setup == "nimbus"    

    - name: delete validator account
      include_role:
        name: delete-validator-keys-prysm
      when: setup == "prysm"

    - name: delete validator account
      include_role:
        name: delete-validator-keys-lodestar
      when: setup == "lodestar"  
    
    - name: delete validator account
      include_role:
        name: delete-validator-keys-nimbus
      when: setup == "nimbus"

    - name: delete validator account
      include_role:
        name: delete-validator-keys-teku
      when: setup == "teku" 
    
    - name: delete validator account
      include_role:
        name: delete-validator-keys-lighthouse
      when: setup == "lighthouse"

    - name: call stop-services role
      include_role:
        name: stop-services
      when: setup == "prysm" or setup == "lodestar" or setup == "teku" or setup == "lighthouse"

    - name: call start-services role
      include_role:
        name: start-services

# EOF
