---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    - name: exit validator account
      include_role:
        name: exit-validator-keys-lighthouse
      when: setup == "lighthouse"

    - name: exit validator account
      include_role:
        name: exit-validator-keys-lodestar
      when: setup == "lodestar" 
    
    - name: exit validator account
      include_role:
        name: exit-validator-keys-prysm
      when: setup == "prysm" 
    
    - name: exit validator account
      include_role:
        name: exit-validator-keys-nimbus
      when: setup == "nimbus"

    - name: exit validator account
      include_role:
        name: exit-validator-keys-teku
      when: setup == "teku"  
