---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    - name: call stop-services role
      include_role:
        name: stop-services

    - name: Get imported keys in variable
      shell: "basename -s .json $(find -name 'keystore-*.json')"
      args:
        chdir: "{{ e2dc_install_path }}/launchpad"
      register: imported_key
      ignore_errors: yes
      become: yes
      when: setup == "teku" 

    - name: temporary copy of keys' name
      copy:
        dest: "{{ e2dc_install_path }}/data/consensys/teku/{{ item.name }}"
        content: ""
      become: yes
      with_items: "{{ validator_keys }}"
      when: validator_keys is defined and setup == "teku"

    - name: Get importing keys in variable web
      shell: "basename -s .json $(find -name 'keystore-*.json')"
      args:
        chdir: "{{ e2dc_install_path }}/data/consensys/teku/"
      register: importing_key_web  
      become: yes
      when: 
        validator_keys is defined and setup == "teku" 

    - name: Remove temporary-copy
      file:
        path: "{{ e2dc_install_path }}/data/consensys/teku/{{ item.name }}"
        state: absent
      become: yes  
      with_items: "{{ validator_keys }}"
      when: setup == "teku" and validator_keys is defined 

    - name: Get importing keys in variable CLI
      shell: "basename -s .json $(find -name 'keystore-*.json')"
      args:
        chdir: "{{ validator_keys_path }}"
      register: importing_key_cli
      become: yes
      when: setup == "teku" and validator_keys is not defined
 
    - name: error web
      fail: 
        msg: 'Choosen account is already imported'
      become: yes  
      with_items: "{{ importing_key_web.stdout_lines }}"
      when: validator_keys is defined and (item in imported_key.stdout_lines and setup == "teku")

    - name: error cli
      fail:
        msg: 'Choosen account is already im'
      become: yes  
      with_items: "{{ importing_key_cli.stdout_lines }}"
      when: validator_keys is not defined and (item in imported_key.stdout_lines and setup == "teku")    

    - name: Create validator keys
      copy:
        dest: "{{ e2dc_install_path }}/launchpad/{{ item.name }}"
        content: "{{ item.content }}"
      become: yes
      with_items: "{{validator_keys}}"
      when: validator_keys is defined   

    - name: Copy lanchpad wallet's validator keys
      shell: "cp {{ validator_keys_path }}/keystore-*.json {{ e2dc_install_path }}/launchpad"
      become: yes
      when: setup != "multiclient" and validator_keys is not defined

    - name: Set permissions of import folder
      shell: "chown -R {{ stereum_user }}:{{ stereum_user }} {{ e2dc_install_path }}/launchpad"
      become: yes
      when: setup != "multiclient"

    - name: import to lighthouse
      include_role:
        name: import-validator-keys-lighthouse
      when: setup == "lighthouse"

    - name: import to lodestar
      include_role:
        name: import-validator-keys-lodestar
      when: setup == "lodestar"

    - name: import to nimbus
      include_role:
        name: import-validator-keys-nimbus
      when: setup == "nimbus"

    - name: import to prysm
      include_role:
        name: import-validator-keys-prysm
      when: setup == "prysm"

    - name: import to teku
      include_role:
        name: import-validator-keys-teku
      when: setup == "teku"
    
    - name: import to multiclient
      include_role:
        name: import-validator-keys-multiclient
      when: setup == "multiclient" 

    - name: call start-services role
      include_role:
        name: start-services

    - name: Pause for 1 minutes to build beacon log
      pause:
        minutes: 1
      become: yes  
      when: setup == "teku"

    - name: Get beacon log in reg_variable
      shell: "docker-compose logs --tail=100 beacon"
      args:
        chdir: "{{ e2dc_install_path }}"
      register: validator_log
      become: yes
      when: setup == "teku"

    - name: Remove keystores files from launchpad web
      file:
        path: "{{ e2dc_install_path }}/launchpad/{{item}}.json"
        state: absent
      become: yes  
      with_items: '{{importing_key_web.stdout_lines}}'
      when: setup == "teku" and (validator_log.stdout is search('Failed to decrypt keystore') and validator_keys is defined)

    - name: Remove password files from launchpad web
      file:
        path: "{{ e2dc_install_path }}/launchpad/{{item}}.txt"
        state: absent
      become: yes  
      with_items: '{{importing_key_web.stdout_lines}}'
      when: setup == "teku" and (validator_log.stdout is search('Failed to decrypt keystore') and validator_keys is defined)  

    - name: Remove keystores files from launchpad cli
      file:
        path: "{{ e2dc_install_path }}/launchpad/{{item}}.json"
        state: absent
      become: yes  
      with_items: '{{importing_key_cli.stdout_lines}}'
      when: setup == "teku" and (validator_log.stdout is search('Failed to decrypt keystore') and validator_keys is not defined)  

    - name: Remove password files from launchpad cli
      file:
        path: "{{ e2dc_install_path }}/launchpad/{{item}}.txt"
        state: absent
      become: yes  
      with_items: '{{importing_key_cli.stdout_lines}}'
      when: setup == "teku" and (validator_log.stdout is search('Failed to decrypt keystore') and validator_keys is not defined)

    - fail:
        msg: 'Incorrect password for account'
      become: yes  
      when: setup == "teku" and validator_log.stdout is search('Failed to decrypt keystore') 

# EOF
