---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    - name: Copy list-account.yaml
      shell: "cp {{ e2dc_install_path }}/compose-examples/prysm-only/list-account.yaml {{ e2dc_install_path }}"
      become: yes
      when: setup == "prysm"

    - name: Copy list-account.yaml
      shell: "cp {{ e2dc_install_path }}/compose-examples/lodestar-only/list-account.yaml {{ e2dc_install_path }}"
      become: yes
      when: setup == "lodestar"

    - name: List accounts prysm
      include_role:
        name: list-validator-keys-prysm
      when: setup == "prysm"

    - name: List accounts lodestar
      include_role:
        name: list-validator-keys-lodestar
      when: setup == "lodestar"

# EOF
