---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  roles:
    - role: stop-services
      stop-services: "{{ setups[setup].services }}"

    - role: start-services
      start-services: "{{ setups[setup].services }}"