---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  # credits to https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Rebooting
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
      when: reboot_required_file.stat.exists

    - name: No reboot needed
      debug:
        msg: No reboot needed!
      when: not reboot_required_file.stat.exists

# EOF
