---
- name: Get imported keys in variable
  shell: "basename -s .json $(find -name 'keystore-*.json')"
  args:
    chdir: "{{ e2dc_install_path }}/launchpad"
  register: imported_key
  ignore_errors: yes
  become: yes

- name: temporary copy of keys' name
  copy:
    dest: "{{ e2dc_install_path }}/data/consensys/teku/{{ item.name }}"
    content: ""
  become: yes
  with_items: "{{ validator_keys }}"
  when: validator_keys is defined

- name: Get importing keys in variable web
  shell: "basename -s .json $(find -name 'keystore-*.json')"
  args:
    chdir: "{{ e2dc_install_path }}/data/consensys/teku/"
  register: importing_key_web
  become: yes
  when: validator_keys is defined

- name: Remove temporary-copy
  file:
    path: "{{ e2dc_install_path }}/data/consensys/teku/{{ item.name }}"
    state: absent
  become: yes
  with_items: "{{ validator_keys }}"
  when: validator_keys is defined

- name: Get importing keys in variable CLI
  shell: "basename -s .json $(find -name 'keystore-*.json')"
  args:
    chdir: "{{ validator_keys_path }}"
  register: importing_key_cli
  become: yes
  when: validator_keys is not defined

- name: error web
  fail:
    msg: 'Choosen account is already imported'
  become: yes
  with_items: "{{ importing_key_web.stdout_lines }}"
  when: validator_keys is defined and item in imported_key.stdout_lines

- name: error cli
  fail:
    msg: 'Choosen account is already imported cli'
  become: yes
  with_items: "{{ importing_key_cli.stdout_lines }}"
  when: validator_keys is not defined and item in imported_key.stdout_lines

# EOF  
