---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: Run import
  command: "./lighthouse_validator_import.sh \"{{ validator_password }}\""
  args:
    chdir: "{{ e2dc_install_path }}"
  register: import_output
  become: yes
  become_user: "{{ stereum_user }}"
  when: setups[setup].create_account is defined

- name: error incorrect password
  fail:
    msg: "Incorrect Password!!! Please check your validator password and try it again."
  become: yes
  when: "'Invalid password' in import_output.stdout"

- name: error account is already imported
  fail:
    msg: "Choosen account is already imported"
  become: yes
  when: "'Skipping import of keystore for existing public key' in import_output.stdout"

# EOF
