---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip
      - expect

- name: Run import
  shell: "./lighthouse_validator_import.sh {{ validator_password | quote }}"
  args:
    chdir: "{{ e2dc_install_path }}"
  register: import_output
  become: yes
  become_user: "{{ stereum_user }}"
  when: setups[setup].create_account is defined

- name: Get keys from launchpad in variable
  find:
    paths: "{{ e2dc_install_path }}/launchpad"
    patterns: "keystore-*.json"
  register: key_files
  become: yes

- name: Removing keys from launchpad
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ key_files.files }}"
  become: yes
  
- name: error incorrect password
  fail:
    msg: "Incorrect Password!!! Please check your validator password and try it again."
  become: yes
  when: "'Invalid password' in import_output.stdout"

- name: error account is already imported
  fail:
    msg: "Choosen account is already imported"
  become: yes
  when: "'Skipping import of keystore for existing public key' in import_output.stdout"

- name: error empty password
  fail:
    msg: "Password is empty!"
  become: yes
  when: import_output.stdout == ""

# EOF
