---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: Run import
  ansible.builtin.expect:
    command: "docker-compose -f create-account.yaml run validator-import-launchpad"
    responses:
      (?i)password: "{{ validator_password }}"
      'Invalid password': "\x03"    
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
  when: setups[setup].create_account is defined 
