---
- name: Run list validators
  command: "docker-compose -f list-account.yaml run validator-list-accounts"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"

# EOF
