---
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - git
  become: yes

- name: Clone Ethereum 2.0 ansible
  git:
    repo: "https://github.com/stereum-dev/ethereum2-ansible.git"
    dest: "{{ e2a_install_path }}"
    force: yes
  become: yes

- name: Change file ownership and group of clone
  file:
    state: directory
    path: "{{ e2a_install_path }}"
    owner: "{{ stereum_user }}"
    group: "{{ stereum_user }}"
    recurse: yes
  become: yes

