---
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - git
  become: yes

- name: Clone Ethereum 2.0 control center cli
  git:
    repo: "https://github.com/stereum-dev/ethereum2-control-center-cli.git"
    dest: "{{ e2ccc_install_path }}"
    force: yes
  become: yes

- name: Change file ownership and group of clone
  file:
    state: directory
    path: "{{ e2ccc_install_path }}"
    owner: "{{ stereum_user }}"
    group: "{{ stereum_user }}"
    recurse: yes
  become: yes

- name: Add stereum control center to local/bin
  file:
    src: "{{ e2ccc_install_path }}/stereum-control-center-cli.sh"
    dest: "/usr/local/bin/stereum-control-center-cli"
    owner: "{{ stereum_user }}"
    group: "{{ stereum_user }}"
    state: link
  become: yes

# EOF
