---
- name: Install expect
  apt:
    name: expect

- name: Run import
  command: "./lodestar_validator_import.sh \"{{ validator_password }}\""
  args:
    chdir: "{{ e2dc_install_path }}"
  register: import_output
  become: yes
  become_user: "{{ stereum_user }}"
  ignore_errors: yes
  when: setups[setup].create_account is defined

- name: error incorrect password
  fail:
    msg: "Incorrect Password!!! Please check your validator password and try it again."
  become: yes
  when: "'Invalid password' in import_output.stdout"

- name: error already imported
  fail:
    msg: "Choosen account is already imported"
  become: yes
  when: "'All validators are already imported' in import_output.stdout"

# EOF
