---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip

- name: Install pexpect
  pip:
    name: pexpect
  vars:
    ansible_python_interpreter: /bin/python3

- name: Set correct permissions
  ansible.builtin.file:
    path: "{{ e2dc_install_path }}/data/nimbus/validator"
    owner: "2000"
    group: "2000"
    mode: '0700'
    state: directory

- name: Run import
  ansible.builtin.expect:
    command: "docker-compose -f create-account.yaml run validator-import-launchpad"
    responses:
      (?i)password: "{{ validator_password }}"
  args:
    chdir: "{{ e2dc_install_path }}"
  vars:
    ansible_python_interpreter: /bin/python3
  become: yes
  become_user: "{{ stereum_user }}"

# EOF
